name = "Hugo Bootstrap 5"
license = "MIT"
licenselink = "https://github.com/kinderdorf-schneckenmuhle-e-v/schnecke-theme-for-hugo/blob/main/LICENSE.md"
description = "Theme for schneckenmuehle.de"
homepage = "http://schneckenmuehle.de"
tags = ["blog", "multilingual", "bootstrap"]
features = ["blog", "responsive", "Google Analytics", "bootstrap", "multilingual", "i18n"]
min_version = 0.91

[author]
  name = "Gregor Suhr"
  homepage = "https://github.com/kinderdorf-schneckenmuhle-e-v/schnecke-theme-for-hugo"

[original]
  author =  "Tiger Oakes"
  homepage = "https://github.com/NotWoods/hugo-bootstrap-5"
  repo = "https://github.com/NotWoods/hugo-bootstrap-5"
